
//
// tokens-expressive-sm-dark.swift
//

// Do not edit directly, this file was auto-generated.


import UIKit

public enum DialtoneTokensExpressiveSmDark {
    public static let dtActionColorBackgroundBaseActive = UIColor(red: 0.671, green: 0.494, blue: 1.000, alpha: 1)
    public static let dtActionColorBackgroundBaseDefault = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0)
    public static let dtActionColorBackgroundBaseHover = UIColor(red: 0.671, green: 0.494, blue: 1.000, alpha: 1)
    public static let dtActionColorBackgroundBasePrimaryActive = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtActionColorBackgroundBasePrimaryDefault = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtActionColorBackgroundBasePrimaryHover = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtActionColorBackgroundCriticalActive = UIColor(red: 0.925, green: 0.055, blue: 0.055, alpha: 1)
    public static let dtActionColorBackgroundCriticalDefault = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0)
    public static let dtActionColorBackgroundCriticalHover = UIColor(red: 0.925, green: 0.055, blue: 0.055, alpha: 1)
    public static let dtActionColorBackgroundCriticalPrimaryActive = UIColor(red: 0.925, green: 0.055, blue: 0.055, alpha: 1)
    public static let dtActionColorBackgroundCriticalPrimaryDefault = UIColor(red: 0.925, green: 0.055, blue: 0.055, alpha: 1)
    public static let dtActionColorBackgroundCriticalPrimaryHover = UIColor(red: 0.925, green: 0.055, blue: 0.055, alpha: 1)
    public static let dtActionColorBackgroundDisabledDefault = UIColor(red: 0.227, green: 0.227, blue: 0.227, alpha: 1)
    public static let dtActionColorBackgroundInvertedActive = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtActionColorBackgroundInvertedDefault = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0)
    public static let dtActionColorBackgroundInvertedHover = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtActionColorBackgroundInvertedPrimaryActive = UIColor(red: 0.227, green: 0.114, blue: 0.584, alpha: 1)
    public static let dtActionColorBackgroundInvertedPrimaryDefault = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtActionColorBackgroundInvertedPrimaryHover = UIColor(red: 0.063, green: 0.008, blue: 0.173, alpha: 1)
    public static let dtActionColorBackgroundMutedActive = UIColor(red: 0.831, green: 0.831, blue: 0.831, alpha: 1)
    public static let dtActionColorBackgroundMutedDefault = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0)
    public static let dtActionColorBackgroundMutedHover = UIColor(red: 0.831, green: 0.831, blue: 0.831, alpha: 1)
    public static let dtActionColorBackgroundPositiveActive = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtActionColorBackgroundPositiveDefault = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0)
    public static let dtActionColorBackgroundPositiveHover = UIColor(red: 0.071, green: 0.275, blue: 0.125, alpha: 1)
    public static let dtActionColorBackgroundPositivePrimaryActive = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtActionColorBackgroundPositivePrimaryDefault = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtActionColorBackgroundPositivePrimaryHover = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtActionColorBorderBaseOutlinedDefault = UIColor(red: 0.671, green: 0.494, blue: 1.000, alpha: 1)
    public static let dtActionColorBorderCriticalOutlinedDefault = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtActionColorBorderInvertedOutlinedDefault = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtActionColorBorderMutedOutlinedDefault = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtActionColorForegroundBaseActive = UIColor(red: 0.671, green: 0.494, blue: 1.000, alpha: 1)
    public static let dtActionColorForegroundBaseDefault = UIColor(red: 0.671, green: 0.494, blue: 1.000, alpha: 1)
    public static let dtActionColorForegroundBaseHover = UIColor(red: 0.671, green: 0.494, blue: 1.000, alpha: 1)
    public static let dtActionColorForegroundBasePrimaryDefault = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtActionColorForegroundCriticalActive = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtActionColorForegroundCriticalDefault = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtActionColorForegroundCriticalHover = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtActionColorForegroundCriticalPrimaryDefault = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtActionColorForegroundDisabledDefault = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtActionColorForegroundInvertedActive = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtActionColorForegroundInvertedDefault = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtActionColorForegroundInvertedHover = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtActionColorForegroundInvertedPrimaryActive = UIColor(red: 0.855, green: 0.780, blue: 1.000, alpha: 1)
    public static let dtActionColorForegroundInvertedPrimaryDefault = UIColor(red: 0.671, green: 0.494, blue: 1.000, alpha: 1)
    public static let dtActionColorForegroundInvertedPrimaryHover = UIColor(red: 0.855, green: 0.780, blue: 1.000, alpha: 1)
    public static let dtActionColorForegroundMutedActive = UIColor(red: 0.761, green: 0.761, blue: 0.761, alpha: 1)
    public static let dtActionColorForegroundMutedDefault = UIColor(red: 0.761, green: 0.761, blue: 0.761, alpha: 1)
    public static let dtActionColorForegroundMutedHover = UIColor(red: 0.761, green: 0.761, blue: 0.761, alpha: 1)
    public static let dtActionColorForegroundPositiveActive = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtActionColorForegroundPositiveDefault = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtActionColorForegroundPositiveHover = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtActionColorForegroundPositivePrimaryDefault = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtAvatarColorBackground000 = UIColor(red: 0.878, green: 0.878, blue: 0.878, alpha: 1)
    public static let dtAvatarColorBackground100 = UIColor(red: 0.102, green: 0.639, blue: 0.251, alpha: 1)
    public static let dtAvatarColorBackground1000 = UIColor(red: 0.714, green: 0.812, blue: 1.000, alpha: 1)
    public static let dtAvatarColorBackground1100 = UIColor(red: 0.945, green: 0.718, blue: 0.910, alpha: 1)
    public static let dtAvatarColorBackground1200 = UIColor(red: 0.925, green: 0.467, blue: 0.741, alpha: 1)
    public static let dtAvatarColorBackground1300 = UIColor(red: 1.000, green: 0.404, blue: 0.745, alpha: 1)
    public static let dtAvatarColorBackground1400 = UIColor(red: 0.973, green: 0.494, blue: 0.494, alpha: 1)
    public static let dtAvatarColorBackground1500 = UIColor(red: 0.925, green: 0.659, blue: 0.467, alpha: 1)
    public static let dtAvatarColorBackground1600 = UIColor(red: 1.000, green: 0.745, blue: 0.255, alpha: 1)
    public static let dtAvatarColorBackground1700 = UIColor(red: 1.000, green: 0.839, blue: 0.275, alpha: 1)
    public static let dtAvatarColorBackground1800 = UIColor(red: 0.945, green: 0.855, blue: 0.718, alpha: 1)
    public static let dtAvatarColorBackground200 = UIColor(red: 0.667, green: 1.000, blue: 0.514, alpha: 1)
    public static let dtAvatarColorBackground300 = UIColor(red: 0.678, green: 0.918, blue: 0.533, alpha: 1)
    public static let dtAvatarColorBackground400 = UIColor(red: 0.467, green: 0.925, blue: 0.651, alpha: 1)
    public static let dtAvatarColorBackground500 = UIColor(red: 0.478, green: 0.929, blue: 0.741, alpha: 1)
    public static let dtAvatarColorBackground600 = UIColor(red: 0.467, green: 0.871, blue: 0.925, alpha: 1)
    public static let dtAvatarColorBackground700 = UIColor(red: 0.369, green: 0.847, blue: 1.000, alpha: 1)
    public static let dtAvatarColorBackground800 = UIColor(red: 0.600, green: 0.906, blue: 1.000, alpha: 1)
    public static let dtAvatarColorBackground900 = UIColor(red: 0.318, green: 0.627, blue: 0.996, alpha: 1)
    public static let dtAvatarColorForeground = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtBadgeColorBackgroundAi = linear-gradient(135deg, UIColor(red: 0.976, green: 0.000, blue: 0.557, alpha: 1) 10%, UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1) 90%)
    public static let dtBadgeColorBackgroundBulletin = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtBadgeColorBackgroundBulletinSubtle = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtBadgeColorBackgroundCritical = UIColor(red: 0.357, green: 0.020, blue: 0.020, alpha: 1)
    public static let dtBadgeColorBackgroundDefault = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtBadgeColorBackgroundInfo = UIColor(red: 0.004, green: 0.196, blue: 0.427, alpha: 1)
    public static let dtBadgeColorBackgroundSuccess = UIColor(red: 0.071, green: 0.275, blue: 0.125, alpha: 1)
    public static let dtBadgeColorBackgroundWarning = UIColor(red: 0.506, green: 0.314, blue: 0.031, alpha: 1)
    public static let dtBadgeColorBorderBulletinSubtle = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtBadgeColorBorderDefault = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtBadgeColorForegroundBulletin = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtBadgeColorForegroundBulletinSubtle = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtBadgeColorForegroundDefault = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtCheckboxColorBackgroundChecked = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtCheckboxColorBorderChecked = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtCheckboxColorBorderUnchecked = UIColor(red: 0.502, green: 0.502, blue: 0.502, alpha: 1)
    public static let dtCheckboxSizeHeight = CGFloat(16.00)
    public static let dtCheckboxSizeRadius = CGFloat(4.00)
    public static let dtCheckboxSizeWidth = CGFloat(16.00)
    public static let dtColorBorderAccent = UIColor(red: 0.976, green: 0.000, blue: 0.557, alpha: 1)
    public static let dtColorBorderAi = linear-gradient(135deg, UIColor(red: 0.976, green: 0.000, blue: 0.557, alpha: 1) 10%, UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1) 90%)
    public static let dtColorBorderBold = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtColorBorderBoldInverted = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtColorBorderBrand = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtColorBorderBrandInverted = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtColorBorderBrandStrong = UIColor(red: 0.855, green: 0.780, blue: 1.000, alpha: 1)
    public static let dtColorBorderBrandStrongInverted = UIColor(red: 0.227, green: 0.114, blue: 0.584, alpha: 1)
    public static let dtColorBorderBrandSubtle = UIColor(red: 0.227, green: 0.114, blue: 0.584, alpha: 1)
    public static let dtColorBorderBrandSubtleInverted = UIColor(red: 0.855, green: 0.780, blue: 1.000, alpha: 1)
    public static let dtColorBorderCritical = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtColorBorderCriticalInverted = UIColor(red: 0.925, green: 0.055, blue: 0.055, alpha: 1)
    public static let dtColorBorderCriticalStrong = UIColor(red: 1.000, green: 0.898, blue: 0.902, alpha: 1)
    public static let dtColorBorderCriticalStrongInverted = UIColor(red: 0.718, green: 0.043, blue: 0.043, alpha: 1)
    public static let dtColorBorderCriticalSubtle = UIColor(red: 0.718, green: 0.043, blue: 0.043, alpha: 1)
    public static let dtColorBorderCriticalSubtleInverted = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtColorBorderDefault = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtColorBorderDefaultInverted = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtColorBorderFocus = UIColor(red: 0.318, green: 0.627, blue: 0.996, alpha: 1)
    public static let dtColorBorderModerate = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtColorBorderModerateInverted = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtColorBorderSubtle = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtColorBorderSubtleInverted = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtColorBorderSuccess = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtColorBorderSuccessInverted = UIColor(red: 0.102, green: 0.639, blue: 0.251, alpha: 1)
    public static let dtColorBorderSuccessStrong = UIColor(red: 0.929, green: 0.976, blue: 0.922, alpha: 1)
    public static let dtColorBorderSuccessStrongInverted = UIColor(red: 0.071, green: 0.275, blue: 0.125, alpha: 1)
    public static let dtColorBorderSuccessSubtle = UIColor(red: 0.102, green: 0.639, blue: 0.251, alpha: 1)
    public static let dtColorBorderSuccessSubtleInverted = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtColorBorderWarning = UIColor(red: 1.000, green: 0.859, blue: 0.502, alpha: 1)
    public static let dtColorBorderWarningInverted = UIColor(red: 0.824, green: 0.561, blue: 0.169, alpha: 1)
    public static let dtColorBorderWarningStrong = UIColor(red: 1.000, green: 0.957, blue: 0.800, alpha: 1)
    public static let dtColorBorderWarningStrongInverted = UIColor(red: 0.506, green: 0.314, blue: 0.031, alpha: 1)
    public static let dtColorBorderWarningSubtle = UIColor(red: 0.824, green: 0.561, blue: 0.169, alpha: 1)
    public static let dtColorBorderWarningSubtleInverted = UIColor(red: 1.000, green: 0.859, blue: 0.502, alpha: 1)
    public static let dtColorForegroundCritical = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtColorForegroundCriticalInverted = UIColor(red: 0.925, green: 0.055, blue: 0.055, alpha: 1)
    public static let dtColorForegroundCriticalStrong = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtColorForegroundCriticalStrongInverted = UIColor(red: 0.718, green: 0.043, blue: 0.043, alpha: 1)
    public static let dtColorForegroundDisabled = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtColorForegroundDisabledInverted = UIColor(red: 0.502, green: 0.502, blue: 0.502, alpha: 1)
    public static let dtColorForegroundMuted = UIColor(red: 0.831, green: 0.831, blue: 0.831, alpha: 1)
    public static let dtColorForegroundMutedInverted = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let dtColorForegroundPlaceholder = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtColorForegroundPlaceholderInverted = UIColor(red: 0.502, green: 0.502, blue: 0.502, alpha: 1)
    public static let dtColorForegroundPrimary = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtColorForegroundPrimaryInverted = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtColorForegroundSecondary = UIColor(red: 0.761, green: 0.761, blue: 0.761, alpha: 1)
    public static let dtColorForegroundSecondaryInverted = UIColor(red: 0.227, green: 0.227, blue: 0.227, alpha: 1)
    public static let dtColorForegroundSuccess = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtColorForegroundSuccessInverted = UIColor(red: 0.102, green: 0.639, blue: 0.251, alpha: 1)
    public static let dtColorForegroundSuccessStrong = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtColorForegroundSuccessStrongInverted = UIColor(red: 0.071, green: 0.275, blue: 0.125, alpha: 1)
    public static let dtColorForegroundTertiary = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtColorForegroundTertiaryInverted = UIColor(red: 0.333, green: 0.333, blue: 0.333, alpha: 1)
    public static let dtColorForegroundWarning = UIColor(red: 1.000, green: 0.859, blue: 0.502, alpha: 1)
    public static let dtColorForegroundWarningInverted = UIColor(red: 0.506, green: 0.314, blue: 0.031, alpha: 1)
    public static let dtColorLinkCritical = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtColorLinkCriticalHover = UIColor(red: 1.000, green: 0.898, blue: 0.902, alpha: 1)
    public static let dtColorLinkCriticalInverted = UIColor(red: 0.925, green: 0.055, blue: 0.055, alpha: 1)
    public static let dtColorLinkCriticalInvertedHover = UIColor(red: 0.718, green: 0.043, blue: 0.043, alpha: 1)
    public static let dtColorLinkDisabled = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtColorLinkDisabledHover = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtColorLinkDisabledInverted = UIColor(red: 0.502, green: 0.502, blue: 0.502, alpha: 1)
    public static let dtColorLinkDisabledInvertedHover = UIColor(red: 0.502, green: 0.502, blue: 0.502, alpha: 1)
    public static let dtColorLinkMuted = UIColor(red: 0.761, green: 0.761, blue: 0.761, alpha: 1)
    public static let dtColorLinkMutedHover = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtColorLinkMutedInverted = UIColor(red: 0.227, green: 0.227, blue: 0.227, alpha: 1)
    public static let dtColorLinkMutedInvertedHover = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtColorLinkPrimary = UIColor(red: 0.671, green: 0.494, blue: 1.000, alpha: 1)
    public static let dtColorLinkPrimaryHover = UIColor(red: 0.855, green: 0.780, blue: 1.000, alpha: 1)
    public static let dtColorLinkPrimaryInverted = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtColorLinkPrimaryInvertedHover = UIColor(red: 0.227, green: 0.114, blue: 0.584, alpha: 1)
    public static let dtColorLinkSuccess = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtColorLinkSuccessHover = UIColor(red: 0.929, green: 0.976, blue: 0.922, alpha: 1)
    public static let dtColorLinkSuccessInverted = UIColor(red: 0.102, green: 0.639, blue: 0.251, alpha: 1)
    public static let dtColorLinkSuccessInvertedHover = UIColor(red: 0.071, green: 0.275, blue: 0.125, alpha: 1)
    public static let dtColorLinkWarning = UIColor(red: 1.000, green: 0.859, blue: 0.502, alpha: 1)
    public static let dtColorLinkWarningHover = UIColor(red: 1.000, green: 0.957, blue: 0.800, alpha: 1)
    public static let dtColorLinkWarningInverted = UIColor(red: 0.506, green: 0.314, blue: 0.031, alpha: 1)
    public static let dtColorLinkWarningInvertedHover = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let dtColorSurfaceBackdrop = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtColorSurfaceBold = UIColor(red: 0.333, green: 0.333, blue: 0.333, alpha: 1)
    public static let dtColorSurfaceBoldOpaque = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtColorSurfaceContrast = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtColorSurfaceContrastOpaque = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtColorSurfaceCritical = UIColor(red: 0.357, green: 0.020, blue: 0.020, alpha: 1)
    public static let dtColorSurfaceCriticalOpaque = UIColor(red: 0.718, green: 0.043, blue: 0.043, alpha: 1)
    public static let dtColorSurfaceCriticalStrong = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtColorSurfaceCriticalSubtle = UIColor(red: 0.357, green: 0.020, blue: 0.020, alpha: 1)
    public static let dtColorSurfaceCriticalSubtleOpaque = UIColor(red: 0.357, green: 0.020, blue: 0.020, alpha: 1)
    public static let dtColorSurfaceInfo = UIColor(red: 0.004, green: 0.196, blue: 0.427, alpha: 1)
    public static let dtColorSurfaceInfoOpaque = UIColor(red: 0.090, green: 0.408, blue: 0.776, alpha: 1)
    public static let dtColorSurfaceInfoStrong = UIColor(red: 0.600, green: 0.784, blue: 1.000, alpha: 1)
    public static let dtColorSurfaceInfoSubtle = UIColor(red: 0.004, green: 0.196, blue: 0.427, alpha: 1)
    public static let dtColorSurfaceInfoSubtleOpaque = UIColor(red: 0.004, green: 0.196, blue: 0.427, alpha: 1)
    public static let dtColorSurfaceModerate = UIColor(red: 0.227, green: 0.227, blue: 0.227, alpha: 1)
    public static let dtColorSurfaceModerateOpaque = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtColorSurfacePrimary = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtColorSurfaceSecondary = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let dtColorSurfaceSecondaryOpaque = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtColorSurfaceStrong = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtColorSurfaceStrongOpaque = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtColorSurfaceSuccess = UIColor(red: 0.071, green: 0.275, blue: 0.125, alpha: 1)
    public static let dtColorSurfaceSuccessOpaque = UIColor(red: 0.102, green: 0.639, blue: 0.251, alpha: 1)
    public static let dtColorSurfaceSuccessStrong = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtColorSurfaceSuccessSubtle = UIColor(red: 0.071, green: 0.275, blue: 0.125, alpha: 1)
    public static let dtColorSurfaceSuccessSubtleOpaque = UIColor(red: 0.071, green: 0.275, blue: 0.125, alpha: 1)
    public static let dtColorSurfaceWarning = UIColor(red: 0.506, green: 0.314, blue: 0.031, alpha: 1)
    public static let dtColorSurfaceWarningOpaque = UIColor(red: 0.824, green: 0.561, blue: 0.169, alpha: 1)
    public static let dtColorSurfaceWarningStrong = UIColor(red: 0.824, green: 0.561, blue: 0.169, alpha: 1)
    public static let dtColorSurfaceWarningSubtle = UIColor(red: 0.506, green: 0.314, blue: 0.031, alpha: 1)
    public static let dtColorSurfaceWarningSubtleOpaque = UIColor(red: 0.506, green: 0.314, blue: 0.031, alpha: 1)
    public static let dtFontSize100 = CGFloat(10.00) * 1.2
    public static let dtFontSize200 = CGFloat(10.00) * 1.6
    public static let dtFontSize300 = CGFloat(10.00) * 2.0
    public static let dtFontSize400 = CGFloat(10.00) * 2.8
    public static let dtFontSize500 = CGFloat(10.00) * 4.1
    public static let dtFontSize600 = CGFloat(10.00) * 5.1
    public static let dtIconSize100 = CGFloat(10.00) * .8 * 1.5
    public static let dtIconSize200 = CGFloat(10.00) * .8 * 1.75
    public static let dtIconSize300 = CGFloat(10.00) * .8 * 2.25
    public static let dtIconSize400 = CGFloat(10.00) * .8 * 2.5
    public static let dtIconSize500 = CGFloat(10.00) * .8 * 3
    public static let dtIconSize600 = CGFloat(10.00) * .8 * 4
    public static let dtIconSize700 = CGFloat(10.00) * .8 * 4.75
    public static let dtIconSize800 = CGFloat(10.00) * .8 * 6
    public static let dtIconSizeBorder100 = CGFloat(1.00)
    public static let dtIconSizeBorder200 = CGFloat(1.00) * 1.25
    public static let dtIconSizeBorder300 = CGFloat(1.00) * 1.5
    public static let dtIconSizeBorder400 = CGFloat(1.00) * 1.75
    public static let dtIconSizeBorder500 = CGFloat(1.00) * 1.75
    public static let dtIconSizeBorder600 = CGFloat(1.00) * 2.5
    public static let dtIconSizeBorder700 = CGFloat(1.00) * 2.75
    public static let dtIconSizeBorder800 = CGFloat(1.00) * 3.5
    public static let dtInputsColorBackgroundDefault = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtInputsColorBackgroundDisabled = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtInputsColorBackgroundFocus = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtInputsColorBorderCritical = UIColor(red: 1.000, green: 0.522, blue: 0.522, alpha: 1)
    public static let dtInputsColorBorderDefault = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtInputsColorBorderDisabled = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0)
    public static let dtInputsColorBorderFocus = UIColor(red: 0.318, green: 0.627, blue: 0.996, alpha: 1)
    public static let dtInputsColorBorderSuccess = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtInputsColorBorderWarning = UIColor(red: 1.000, green: 0.859, blue: 0.502, alpha: 1)
    public static let dtInputsColorForegroundDefault = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtInputsColorForegroundDisabled = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtInputsColorForegroundPlaceholder = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtInputsFontSizeLg = CGFloat(10.00) * 2.0
    public static let dtInputsFontSizeMd = CGFloat(10.00) * 1.6
    public static let dtInputsFontSizeSm = CGFloat(10.00) * 1.2
    public static let dtInputsFontSizeXl = CGFloat(10.00) * 1.2
    public static let dtInputsFontSizeXs = CGFloat(10.00) * 1.2
    public static let dtInputsLineHeightDefault = CGFloat(120.00)
    public static let dtInputsSizeBorderDefault = CGFloat(1.50)
    public static let dtInputsSizeBorderStatus = CGFloat(2.00)
    public static let dtInputsSizeRadiusLg = CGFloat(4.00) * 3
    public static let dtInputsSizeRadiusMd = CGFloat(8.00)
    public static let dtInputsSizeRadiusSm = CGFloat(8.00)
    public static let dtInputsSizeRadiusXl = CGFloat(16.00)
    public static let dtInputsSizeRadiusXs = CGFloat(4.00)
    public static let dtRadioColorBackgroundChecked = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtRadioColorBorderChecked = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtRadioColorBorderUnchecked = UIColor(red: 0.502, green: 0.502, blue: 0.502, alpha: 1)
    public static let dtRadioSizeHeight = CGFloat(16.00)
    public static let dtRadioSizeRadius = CGFloat(50.00)
    public static let dtRadioSizeWidth = CGFloat(16.00)
    public static let dtSizeBorderFocus = CGFloat(2.00) + CGFloat(1.00)
    public static let dtThemeColorBase = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeMentionColorBackground = UIColor(red: 0.486, green: 0.322, blue: 1.000, alpha: 1)
    public static let dtThemeMentionColorBackgroundStrong = UIColor(red: 0.855, green: 0.780, blue: 1.000, alpha: 1)
    public static let dtThemeMentionColorForeground = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtThemeMentionColorForegroundStrong = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtThemePresenceColorBackgroundAvailable = UIColor(red: 0.690, green: 1.000, blue: 0.639, alpha: 1)
    public static let dtThemePresenceColorBackgroundBusy = UIColor(red: 0.965, green: 0.671, blue: 0.235, alpha: 1)
    public static let dtThemePresenceColorBackgroundBusyUnavailable = UIColor(red: 0.925, green: 0.055, blue: 0.055, alpha: 1)
    public static let dtThemePresenceColorBackgroundOffline = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let dtThemeSidebarColorBackground = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let dtThemeSidebarColorForeground = UIColor(red: 0.761, green: 0.761, blue: 0.761, alpha: 1)
    public static let dtThemeSidebarColorForegroundUnread = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeSidebarIconColorForeground = UIColor(red: 0.761, green: 0.761, blue: 0.761, alpha: 1)
    public static let dtThemeSidebarRowColorBackground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeSidebarRowColorBackgroundActive = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeSidebarRowColorBackgroundHover = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeSidebarSectionColorForeground = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtThemeSidebarSelectedRowColorBackground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeSidebarSelectedRowColorForeground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeSidebarStatusColorForeground = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1)
    public static let dtThemeTopbarButtonColorBackground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarButtonColorBackgroundActive = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarButtonColorBackgroundHover = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarButtonColorForeground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarButtonColorForegroundHover = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarColorBackground = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let dtThemeTopbarColorForeground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarFieldColorBackground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarFieldColorBackgroundHover = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let dtThemeTopbarFieldColorBorder = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarFieldColorBorderActive = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarFieldColorBorderHover = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarFieldColorForeground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarFieldColorForegroundHover = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarProfileColorBackground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarProfileColorBackgroundActive = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarProfileColorBackgroundHover = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarProfileColorBackgroundInverted = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarProfileColorForeground = UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1)
    public static let dtThemeTopbarProfileColorForegroundInverted = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let dtTypographyBodyMdCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyBodyMdCompactFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyBodyMdCompactFontWeight = 400
    public static let dtTypographyBodyMdCompactLineHeight = CGFloat(140.00)
    public static let dtTypographyBodyMdCompactTextCase = "none"
    public static let dtTypographyBodyMdFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyBodyMdFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyBodyMdFontWeight = 400
    public static let dtTypographyBodyMdLineHeight = CGFloat(160.00)
    public static let dtTypographyBodyMdTextCase = "none"
    public static let dtTypographyBodySmCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyBodySmCompactFontSize = CGFloat(10.00) * 1.2
    public static let dtTypographyBodySmCompactFontWeight = 400
    public static let dtTypographyBodySmCompactLineHeight = CGFloat(120.00)
    public static let dtTypographyBodySmCompactTextCase = "none"
    public static let dtTypographyBodySmFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyBodySmFontSize = CGFloat(10.00) * 1.2
    public static let dtTypographyBodySmFontWeight = 400
    public static let dtTypographyBodySmLineHeight = CGFloat(140.00)
    public static let dtTypographyBodySmTextCase = "none"
    public static let dtTypographyCodeMdFontFamily = UIFont.monospacedSystemFont(ofSize: 15, weight: .regular)
    public static let dtTypographyCodeMdFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyCodeMdFontWeight = 400
    public static let dtTypographyCodeMdLineHeight = CGFloat(120.00)
    public static let dtTypographyCodeMdTextCase = "none"
    public static let dtTypographyCodeSmFontFamily = UIFont.monospacedSystemFont(ofSize: 15, weight: .regular)
    public static let dtTypographyCodeSmFontSize = CGFloat(10.00) * 1.2
    public static let dtTypographyCodeSmFontWeight = 400
    public static let dtTypographyCodeSmLineHeight = CGFloat(120.00)
    public static let dtTypographyCodeSmTextCase = "none"
    public static let dtTypographyHeadlineEyebrowFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineEyebrowFontSize = CGFloat(10.00) * 1.2
    public static let dtTypographyHeadlineEyebrowFontWeight = 400
    public static let dtTypographyHeadlineEyebrowLineHeight = CGFloat(140.00)
    public static let dtTypographyHeadlineEyebrowTextCase = "uppercase"
    public static let dtTypographyHeadlineLgCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineLgCompactFontSize = CGFloat(10.00) * 2.8
    public static let dtTypographyHeadlineLgCompactFontWeight = 700
    public static let dtTypographyHeadlineLgCompactLineHeight = CGFloat(140.00)
    public static let dtTypographyHeadlineLgCompactTextCase = "none"
    public static let dtTypographyHeadlineLgFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineLgFontSize = CGFloat(10.00) * 2.8
    public static let dtTypographyHeadlineLgFontWeight = 700
    public static let dtTypographyHeadlineLgLineHeight = CGFloat(160.00)
    public static let dtTypographyHeadlineLgSoftCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineLgSoftCompactFontSize = CGFloat(10.00) * 2.8
    public static let dtTypographyHeadlineLgSoftCompactFontWeight = 500
    public static let dtTypographyHeadlineLgSoftCompactLineHeight = CGFloat(140.00)
    public static let dtTypographyHeadlineLgSoftCompactTextCase = "none"
    public static let dtTypographyHeadlineLgSoftFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineLgSoftFontSize = CGFloat(10.00) * 2.8
    public static let dtTypographyHeadlineLgSoftFontWeight = 500
    public static let dtTypographyHeadlineLgSoftLineHeight = CGFloat(160.00)
    public static let dtTypographyHeadlineLgSoftTextCase = "none"
    public static let dtTypographyHeadlineLgTextCase = "none"
    public static let dtTypographyHeadlineMdCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineMdCompactFontSize = CGFloat(10.00) * 2.0
    public static let dtTypographyHeadlineMdCompactFontWeight = 700
    public static let dtTypographyHeadlineMdCompactLineHeight = CGFloat(140.00)
    public static let dtTypographyHeadlineMdCompactTextCase = "none"
    public static let dtTypographyHeadlineMdFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineMdFontSize = CGFloat(10.00) * 2.0
    public static let dtTypographyHeadlineMdFontWeight = 700
    public static let dtTypographyHeadlineMdLineHeight = CGFloat(160.00)
    public static let dtTypographyHeadlineMdTextCase = "none"
    public static let dtTypographyHeadlineSmCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineSmCompactFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyHeadlineSmCompactFontWeight = 700
    public static let dtTypographyHeadlineSmCompactLineHeight = CGFloat(120.00)
    public static let dtTypographyHeadlineSmCompactTextCase = "none"
    public static let dtTypographyHeadlineSmFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineSmFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyHeadlineSmFontWeight = 700
    public static let dtTypographyHeadlineSmLineHeight = CGFloat(140.00)
    public static let dtTypographyHeadlineSmSoftCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineSmSoftCompactFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyHeadlineSmSoftCompactFontWeight = 500
    public static let dtTypographyHeadlineSmSoftCompactLineHeight = CGFloat(120.00)
    public static let dtTypographyHeadlineSmSoftCompactTextCase = "none"
    public static let dtTypographyHeadlineSmSoftFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineSmSoftFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyHeadlineSmSoftFontWeight = 500
    public static let dtTypographyHeadlineSmSoftLineHeight = CGFloat(140.00)
    public static let dtTypographyHeadlineSmSoftTextCase = "none"
    public static let dtTypographyHeadlineSmTextCase = "none"
    public static let dtTypographyHeadlineXlCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineXlCompactFontSize = CGFloat(10.00) * 4.1
    public static let dtTypographyHeadlineXlCompactFontWeight = 500
    public static let dtTypographyHeadlineXlCompactLineHeight = CGFloat(100.00)
    public static let dtTypographyHeadlineXlCompactTextCase = "none"
    public static let dtTypographyHeadlineXlFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineXlFontSize = CGFloat(10.00) * 4.1
    public static let dtTypographyHeadlineXlFontWeight = 500
    public static let dtTypographyHeadlineXlLineHeight = CGFloat(120.00)
    public static let dtTypographyHeadlineXlTextCase = "none"
    public static let dtTypographyHeadlineXxlCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineXxlCompactFontSize = CGFloat(10.00) * 5.1
    public static let dtTypographyHeadlineXxlCompactFontWeight = 500
    public static let dtTypographyHeadlineXxlCompactLineHeight = CGFloat(100.00)
    public static let dtTypographyHeadlineXxlCompactTextCase = "none"
    public static let dtTypographyHeadlineXxlFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHeadlineXxlFontSize = CGFloat(10.00) * 5.1
    public static let dtTypographyHeadlineXxlFontWeight = 500
    public static let dtTypographyHeadlineXxlLineHeight = CGFloat(120.00)
    public static let dtTypographyHeadlineXxlTextCase = "none"
    public static let dtTypographyHelperMdFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHelperMdFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyHelperMdFontWeight = 400
    public static let dtTypographyHelperMdLineHeight = CGFloat(140.00)
    public static let dtTypographyHelperMdTextCase = "none"
    public static let dtTypographyHelperSmFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyHelperSmFontSize = CGFloat(10.00) * 1.2
    public static let dtTypographyHelperSmFontWeight = 400
    public static let dtTypographyHelperSmLineHeight = CGFloat(120.00)
    public static let dtTypographyHelperSmTextCase = "none"
    public static let dtTypographyLabelMdCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyLabelMdCompactFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyLabelMdCompactFontWeight = 600
    public static let dtTypographyLabelMdCompactLineHeight = CGFloat(140.00)
    public static let dtTypographyLabelMdCompactTextCase = "none"
    public static let dtTypographyLabelMdFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyLabelMdFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyLabelMdFontWeight = 600
    public static let dtTypographyLabelMdLineHeight = CGFloat(160.00)
    public static let dtTypographyLabelMdPlainCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyLabelMdPlainCompactFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyLabelMdPlainCompactFontWeight = 400
    public static let dtTypographyLabelMdPlainCompactLineHeight = CGFloat(140.00)
    public static let dtTypographyLabelMdPlainCompactTextCase = "none"
    public static let dtTypographyLabelMdPlainFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyLabelMdPlainFontSize = CGFloat(10.00) * 1.6
    public static let dtTypographyLabelMdPlainFontWeight = 400
    public static let dtTypographyLabelMdPlainLineHeight = CGFloat(160.00)
    public static let dtTypographyLabelMdPlainTextCase = "none"
    public static let dtTypographyLabelMdTextCase = "none"
    public static let dtTypographyLabelSmCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyLabelSmCompactFontSize = CGFloat(10.00) * 1.2
    public static let dtTypographyLabelSmCompactFontWeight = 600
    public static let dtTypographyLabelSmCompactLineHeight = CGFloat(120.00)
    public static let dtTypographyLabelSmCompactTextCase = "none"
    public static let dtTypographyLabelSmFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyLabelSmFontSize = CGFloat(10.00) * 1.2
    public static let dtTypographyLabelSmFontWeight = 600
    public static let dtTypographyLabelSmLineHeight = CGFloat(140.00)
    public static let dtTypographyLabelSmPlainCompactFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyLabelSmPlainCompactFontSize = CGFloat(10.00) * 1.2
    public static let dtTypographyLabelSmPlainCompactFontWeight = 400
    public static let dtTypographyLabelSmPlainCompactLineHeight = CGFloat(120.00)
    public static let dtTypographyLabelSmPlainCompactTextCase = "none"
    public static let dtTypographyLabelSmPlainFontFamily = Archivo, UIFont.systemFont(ofSize: 15)
    public static let dtTypographyLabelSmPlainFontSize = CGFloat(10.00) * 1.2
    public static let dtTypographyLabelSmPlainFontWeight = 400
    public static let dtTypographyLabelSmPlainLineHeight = CGFloat(140.00)
    public static let dtTypographyLabelSmPlainTextCase = "none"
    public static let dtTypographyLabelSmTextCase = "none"
}